TNK<- as.matrix(GetAssayData(AAandHDandPBandBM, slot = "counts")[, WhichCells(AAandHDandPBandBM, idents = c("0","1","10","13","19","25","26"))])
TNK [c("PAX5", "RUNX1", "HOXA9"), 1:30]
TNK <- CreateSeuratObject(counts =TNK, project = "TandNK", min.cells = 3, min.features = 200)
TNK[["percent.mt"]] <- PercentageFeatureSet(TNK, pattern = "^MT-")
VlnPlot(TNK, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
TNK <- subset(TNK, subset = nFeature_RNA > 200 & nFeature_RNA < 10000 & percent.mt < 25)
saveRDS(TNK, file = "TNK-step1.RDS")
rm(list = ls())
gc()
TNK <- readRDS("TNK-step1.RDS")
TNK <- NormalizeData(TNK) %>% FindVariableFeatures() %>% ScaleData()%>% SCTransform(vars.to.regress = "percent.mt") %>% RunPCA() %>% FindNeighbors(dims = 1:30) 
library(harmony)
library(Seurat)
library(ggplot2)
library(data.table)
library(BiocManager)
library(magrittr)
library(dplyr)
library(stringr)
librem.time({TNK <- RunHarmony(TNK, group.by.vars = "orig.ident")})
TNK <- RunUMAP(TNK, reduction = "harmony", dims = 1:50)
save<- FindNeighbors(TNK, reduction = "harmony", dims = 1:50) %>% FindClusters(resolution=0.5)
DimPlot(TNK, reduction = "umap", label=T,pt.size=2)
DimPlot(TNK, reduction = "umap", label=T,split.by='orig.ident',pt.size=2)
sce.markers <- FindAllMarkers(TNK, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)